### ISSUE TITLE
Document updates not working when extending another document

### ISSUE THREAD

**Issue by lenardpalko** [doctrine/mongodb-odm#1064]
I have the following setup : 
A document `BoosterTerm` extending document `Term`, and every `BoosterTerm` can have a `BoosterTerm` as a parent.

Now the issue is when I get $boosterTerm->getParent() and update a value on it and then flush the value is not saved in the DB, there is no exception, no error, the values are simply not saved in the DB.

Here are some code examples : 
```yaml
Acme\Bundle\Document\Term:
    repositoryClass: Acme\Bundle\Repository\TermRepository
    collection: terms
    type: document
    inheritanceType: COLLECTION_PER_CLASS
    fields:
        id:
            id: true
        name:
            type: string
        parent:
            reference: true
            type: one
            nullable: true
            targetDocument: Acme\Bundle\Document\Term
```
```yaml
Acme\Bundle\Document\BoosterTerm:
    repositoryClass: Acme\Bundle\Repository\BoosterTermRepository
    collection: booster_terms
    type: document
    fields:
        id:
            id: true
        creation:
            type: boolean
        parent:
            reference: true
            type: one
            targetDocument: Acme\Bundle\Document\BoosterTerm
            inversedBy: children
        children:
            reference: true
            type: many
            targetDocument: Acme\Bundle\Document\BoosterTerm
            mappedBy: parent
```

```php
<?php
class BoosterTerm extends Term
```

After digging a while I think I found what the issue is, but not sure where the source of the issue is.
In `Doctrine/ODM/MongoDB/UnitOfWork.php` in function `executeUpdates` on line `1186` in the master-dev version.

```php
if (get_class($document) == $className || $document instanceof Proxy && $document instanceof $className) {
```
evaluates as true for a `BoosterTerm` document when `$className` is actually `Acme\Bundle\Document\Term` and it continues until `Doctrine/MongoDB/Collection.php` line `1243` :
```php
return $this->mongoCollection->update($query, $newObj, $options);
```

but after that line is executed nothing happens in the DB.

I've made it work only after I removed the `Acme\Bundle\Document\Term` from the `$commitOrder` array in `UnitOfWork`.

So there migth be three sources of the issue :
1. `Acme\Bundle\Document\Term` should not appear in `$commitOrder` as no Document with this type has been modified.
2. the order in the `$commitOrder` is not ok as `Acme\Bundle\Document\Term` appears before `Acme\Bundle\Document\BoosterTerm`
3. line `1186` in UnitOfWork should match only the instance of the child class and not the parent class also.

I hope this really is an issue and you can understand what is happening.

I would like to work on this issue if somebody would guide me a little between the 3 above solutions.
