### ISSUE TITLE
How to add @Distance in yaml  mapping file?

### ISSUE THREAD

**Issue by mrcmorales** [doctrine/mongodb-odm#1082]
Hi,

How I can add @Distance  in yaml mapping file ? I tried it and not works.

```CP\AppBundle\Document\Point:
  type: embeddedDocument
  embedOne:
    address:
      targetDocument: CP\AppBundle\Document\Address
    coordinates:
      targetDocument: CP\AppBundle\Document\Coordinates
  distance: distance
  indexes:
    coordinates:
      keys:
        coordinates: 2d
```

(edit @alcaeus): wrapped mapping in code tags for readability

**Comment by mrcmorales** [comment]
hi @jwage, 

Do you know if @Distance works with yaml mapping ?

Thanks

**Comment by alcaeus** [comment]
Have you tried this?
```
CP\AppBundle\Document\Point:
  type: embeddedDocument
  fields:
    distance:
      distance: true
  embedOne:
    address:
      targetDocument: CP\AppBundle\Document\Address
    coordinates:
      targetDocument: CP\AppBundle\Document\Coordinates
  indexes:
    coordinates:
      keys:
        coordinates: 2d
```

You have to specify a field which will store the distance and mark that with ```distance: true```

**Comment by mrcmorales** [comment]
Thanks, it works.

**Comment by rickogden** [comment]
This does not work for me, I get an "undefined index: type" error message.

**Comment by malarzm** [comment]
@rickogden from error it seems like you are missing "type" in your mapping.

**Comment by rickogden** [comment]
@malarzm: What should the type be set to for a distance field? I was thinking that type wasn't specified for the distance field as it's dynamically generated.

**Comment by malarzm** [comment]
@rickogden are you sure the error is related with distance?

**Comment by rickogden** [comment]
@malarzm: solved it. It needs to be:

```
fields:
    distance:
      distance: true
      type: float
```
