### ISSUE TITLE
Broken ODM schema produces different results with and without schema caching

### ISSUE THREAD

**Issue by pilou** [doctrine/mongodb-odm#1271]
On dev enviroment we don't use MetadataCache, but in production we do.
The problem is that the schema genereated from yaml files seems to be okay in dev, but fails on production.
The first request is okay when there is no cache yet, but when the schema is read from cache sometimes there are errors that are not experienced without caching.
By saying "using no cache" I mean either setting ArrayCache, or setting other caching methods like Filesystem cache or Mongodb cache but clearing all entries before running the script.

In the example below you can see a schema with inheritance, with some lines commented out.
I know that they are invalid without the commented lines, but it works when caching is not enabled.
When retrieving documents from DB without cache (even if I caching is on but empty), I get the correct hydrated objects, but when using caching, ODM tries to hydrate the document as Document\Font\Family (the superclass)  

```
Document\Font\Family:
#  type: mappedSuperclass
#  inheritanceType: SINGLE_COLLECTION
  collection: FontFamily
  repositoryClass: Repository\Font\Family
  discriminatorField: _t
  discriminatorMap:
      system: Document\Font\Family\System
      google: Document\Font\Family\Google
      uploaded: Document\Font\Family\Uploaded
  fields:
    id:
      id: true
      strategy: AUTO
    name:
      type: string
      name: n
    wysiwygSafe:
      type: boolean
      name: ws

Document\Font\Family\Google:
  collection: FontFamily
#  inheritanceType: SINGLE_COLLECTION
  repositoryClass: Repository\Font\Family

Document\Font\Family\System:
  collection: FontFamily
#  inheritanceType: SINGLE_COLLECTION
  repositoryClass: Repository\Font\Family

Document\Font\Family\Uploaded:
  collection: FontFamily
#  inheritanceType: SINGLE_COLLECTION
  repositoryClass: Repository\Font\Family
  fields:
      md5:
          type: string
          name: md5
```

It is absolutely clear that the problem is with the missing attrbutes (inheritanceType, type: mappedSuperclass), but the sad thing is that we encounter the problem on production env only.

Is there a way that we validate the schema with a cli tool, or to make the caching system so that ODM produces the same results with and without caching (even if the schema is invalid)?
