### ISSUE TITLE
NONE strategy for ID field is not applied

### ISSUE THREAD

**Issue by olysyuk** [doctrine/mongodb-odm#1295]
When I create 
```
$c = new MyPersistentClass();
$c->setId('My Text ID');
$dm->persist($c);
$dm->flush();
```
With metadata:
```
MyPersistentClass:
  fields:
    id:
      id: true
      strategy: NONE
```

Everything works fine and I get { "_id" : "My Text ID" }. 

Once i add `type: id` to metadata mapping:
```
MyPersistentClass:
  fields:
    id:
      id: true
      type: id
      strategy: NONE
```

It starts generating regular Mongo IDs without regard to strategy setting: 
{ "_id" : ObjectId("56602b30e3c252b44d0041a8")
