### ISSUE TITLE
$elemMatch is not returning results

### ISSUE THREAD

**Issue by pablomoreno61** [doctrine/mongodb-odm#1423]
Hi,

I'm doing a query like this:

```
$qb = $this->getDocumentManager()->createQueryBuilder('CSP\Domain\User\Document\User');
$qb = $this->getUserQueryBuilder()
    ->select(array('featureds'));

$qb
    ->field('featureds')
    ->elemMatch(
        $qb->expr()
            ->field('isActive')->equals(true)
            ->field('expireAt')->gte($range->getStartDate())
            ->field('expireAt')->lt($range->getEndDate())
);

return $qb->getQuery()->execute();
```

But it is returning as empty.

My embedded document has the properties defined:

```
Featured:
    type: embeddedDocument
    fields:
    isActive:
        name: is_active
        type: boolean
    expireAt:
        name: expire_at
       type: date
```

I've tested my query using the is_active and expire_at field names and it works. Why using the camelCase field names doesn't works?
