### ISSUE TITLE
CreateQueryBuilder sorting not working for EmbedMany document

### ISSUE THREAD

**Issue by thim81** [doctrine/mongodb-odm#1522]
When trying to sort the embed documents, the sorting is not respected.

```
        $qb = $this->dm->createQueryBuilder(
          'User'
        );

        // Filter by ID
        $qb->addAnd($qb->expr()->field('_id')->equals($userId));

        // Sorting
        $qb->sort(['addresses.type' => 'desc']);

        // Get document
        $document = $qb->getQuery()->getSingleResult();

        return $document;
```

We have a "user" document which embed all "addresses" of a user.
I want to sort the addresses by type.

User.mongodb.yml

```
CoreBundle\Document\User:
  type: document

  embedMany:
      addresses:
          targetDocument: Address

  fields:
      id:
          id:   true
      firstName:
          type: string

      surName:
          type: string
```

Address.mongodb.yml

```
CoreBundle\Document\Address:
  type: embeddedDocument

  fields:
      id:
          type: id
          id: true

      type:
          type: int
          index: true

      name:
          type: string

      street:
          type: string

      streetNumber:
          type: string
```

Is this a bug?
