### ISSUE TITLE
Get id of last inserted document using createQueryBuilder

### ISSUE THREAD

**Issue by felixveysseyre** [doctrine/mongodb-odm#1526]
Hello,

This more a question than a bug. I already post my question on [StackOverflow](http://stackoverflow.com/questions/40591883/get-id-of-the-mongodb-document-created-in-a-symfony3-repository) but I did not get any answer, therefore I am trying here.

In a _Symfony3_ project, I am using _Doctrine_ to handle my _MongoDB_ database.

I do have the following document:
```
UserBundle\Document\User:
    repositoryClass: UserBundle\Repository\UserRepository
    fields:
        userId:
            id: true
        email:
            type: string
        firstName:
            type: string
        lastName:
            type: string
```

Some time I need to create my document in my repository, therefore I built the following method, using _createQueryBuilder_:

```
public function insert($email, $firstName, $lastName)
{
    $data = array(
        'email' => $email,
        'firstName' => $firstName,
        'lastName' => $lastName,
    );

    /* Create query */

    $query = $this->createQueryBuilder();

    /* Add Data */

    $query
        ->insert()
        ->setNewObj($data);

    /* Return */

    $query
        ->getQuery()
        ->execute();

    return true;
}
```

Instead of returning `true`, I would like to **return the Id of the inserted document** (or the complete document). Looking around I did not found any answer to my problem.

Does any one know if this behavior is possible ?

Thanks,
Félix
