### ISSUE TITLE
Error in doctrine:mongodb:generate:documents

### ISSUE THREAD

**Issue by salehsed** [doctrine/mongodb-odm#161]
in my project, i tried to use

```
  app/console   doctrine:mongodb:generate:documents CoTestBundle --document="Test"
```
## error

```


  [ErrorException]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  Catchable Fatal Error: Argument 1 passed to Doctrine\ODM\MongoDB\Mapping\Driver\YamlDriver::addFieldMapping() must be an instance of Doctrine\ODM\MongoDB\Mapping\ClassMetadata, instance of Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo given, called in /apps/myproj/vendor/doctrine-mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php on line 104 and defined in /apps/myproj/vendor/doctrine-mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php line 136  



```

the Yml file is :

```
Co\TestBundle\Document\Test:
    fields:
        id:
            id:  true
        name:
            type: string
        price:
            type: float
```
