### ISSUE TITLE
Add the ability to configure custom data types via config file

### ISSUE THREAD

**Issue by TheHett** [doctrine/mongodb-odm#1766]
it would be very convenient to be able to configure custom data types like in the dbal
https://symfony.com/doc/current/doctrine/dbal.html
```
doctrine:
    dbal:
        types:
            custom_first:  App\Type\CustomFirst
            custom_second: App\Type\CustomSecond
```
