### ISSUE TITLE
Protected properties in MappedSuperClass

### ISSUE THREAD

**Issue by etshy** [doctrine/mongodb-odm#1921]
I had my Documents using Annotation Mappings, have my "BaseDocument" with protected properties.
Everything worked well with Annotations.
I recently changed to XML mapping, and now the properties in my "BaseDocument" are undefined (`$id` property).

May be related to https://github.com/doctrine/mongodb-odm/issues/918 I guess, but why protected properties would work with Annotations mapping and not with XML mapping ?

I can't try to change my protected properties to private right now, but it seems the problems came from changing from Annotation to XML.

Will be able to put more info in few hours, if needed.

**Comment by malarzm** [comment]
@etshy a failing test case would be the best way to go forward with this

**Comment by alcaeus** [comment]
@etshy please fill out the respective issue templates: this has the advantage of us knowing what version you are using. 1.x or 2.x makes a big difference here.

**Comment by etshy** [comment]
I'll fill info such as version and my code asap.

I'll try to make a quick reproduction too.

**Comment by etshy** [comment]
Here is more info.

Doctrine ODM bundle version (from `composer show`) : * 3.5.x-dev
Doctrine mongodb-odm version : * 1.2.5
Doctrine mongodb version : * 1.6.3

Seems like changing my properties to `private` didn't help at the end ... So I have absolutely no idea what could go wrong, but as I followed the doc, I guess this issue is still "valid"

Here are some code
BaseModel:
```
<?php

namespace App\Model\Persistence;

abstract class BaseModel
{
    /**
     * @var string
     */
    private $id;
    
    /**
     * @var \DateTime
     */
    private $createdAt;
    
    /**
     * @var \DateTime
     */
    private $updatedAt;
    //Getters/setters ...
}
```

The mapping file BaseModel.mongodb.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<doctrine-mongo-mapping xmlns="http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping
                http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping.xsd">
<mapped-superclass name="App\Model\Persistence\BaseModel">
    <field fieldName="id" id="true" unique="true"/>
    <field fieldName="createdAt" type="date"/>
    <field fieldName="updatedAt" type="date"/>
</mapped-superclass>
</doctrine-mongo-mapping>
```

And one of my "subClass"

```
<?php

namespace App\Model\Persistence;

...
use Symfony\Component\Validator\Constraints as Assert;

class Chapter extends BaseModel
{
    
    /**
     * @var string|null
     * @Assert\Type("string")
     */
    protected $name;
    
    /**
     * @var int|null
     * @Assert\NotBlank()
     * @Assert\Type("int")
     */
    protected $number;
    
    ...
}
```

and the mapping file Chapter.mongodb.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<doctrine-mongo-mapping xmlns="http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping
                http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping.xsd">
    <document name="App\Model\Persistence\Chapter" repository-class="App\Model\ODM\Repository\ChapterRepository">
        <field name="name" type="string"/>
        <field name="number" type="int"/>
        ...
    </document>

</doctrine-mongo-mapping>
```

And my doctrine_mongodb.yaml
```
doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options: {}
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/src/Model/Mapping/ODM'
                    prefix: App\Model\Persistence
```

About the reproduction, is there a "basic repo" to clone for it ?
If not I'll just create a new symfony project and add DoctrineODMBundle, and try to reproduce my issue.
