### ISSUE TITLE
The class "Doctrine\ODM\MongoDB\PersistentCollection" was not found in the chain configured namespaces App\Document"

### ISSUE THREAD

**Issue by Oihso** [doctrine/mongodb-odm#2036]
|    Q        |   A
|------------ | -----
| Version     | 1.2.9
| Framework | Symfony 4
| PHP | 7.2

### Support Question

I created a class to update the cart object. When I try to update an object that is already stored in the database, I get an error `The class "Doctrine\ODM\MongoDB\PersistentCollection" was not found in the chain configured namespaces App\Document"`. This error occurs only with the cart object (And only during the object update. Creating a new object runs without problems), although there are similar objects in the project that do not cause such a problem.

In addition to this error, I discovered a few more:

1. This error occurs only when you try to update a field of type "EmbedMany". An attempt to update all other fields passed without errors. Also, any operations with any other objects go without problems.
2. When I tried to use QueryBuilder, I got the error `Class 'Cart' does not exist`

Cart class:
```php
namespace App\Document;

use DateTime;
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

/**
 * @MongoDB\EmbeddedDocument()
 */
class CartItem
{
    /**
     * @MongoDB\Field(type="string")
     */
    private $productId;

    /**
     * @MongoDB\Field(type="integer")
     */
    private $quantity;

    // More fields ...

    /**
     * @return string
     */
    public function getProductId(): string
    {
        return $this->productId;
    }

    /**
     * @param string $productId
     * @return CartItem
     */
    public function setProductId($productId): CartItem
    {
        $this->productId = $productId;
        return $this;
    }

    /**
     * @return int
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * @param int $quantity
     * @return CartItem
     */
    public function setQuantity(int $quantity): CartItem
    {
        $this->quantity = $quantity;
        return $this;
    }

    // More getters and setters ...
}

/**
 * @MongoDB\Document()
 */
class Cart
{
    /**
     * @MongoDB\Id
     */
    private $id;

    /**
     * @MongoDB\Field(type="string")
     */
    private $hash;

    /**
     * @MongoDB\Field(type="date")
     */
    private $date;

    // More fields ...

    /**
     * 'Bad' field
     * @MongoDB\EmbedMany(targetDocument="CartItem")
     */
    private $products;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getHash(): ?string 
    {
        return $this->hash;
    }

    /**
     * @param string $hash
     * @return Cart
     */
    public function setHash(string $hash): Cart
    {
        $this->hash = $hash;
        return $this;
    }

    /**
     * @return DateTime
     */
    public function getDate(): DateTime
    {
        return $this->date;
    }

    /**
     * @param DateTime $date
     * @return Cart
     */
    public function setDate(DateTime $date): Cart
    {
        $this->date = $date;
        return $this;
    }

    // More getters and setters

    /**
     * @return CartItem[]|null
     */
    public function getProducts(): ?array
    {
        return $this->products;
    }

    /**
     * @param CartItem[] $products
     * @return Cart
     */
    public function setProducts(array $products): Cart
    {
        $this->products = $products;
        return $this;
    }
}
```

The class for updating an cart object is just a set of business logic (After checking, it turned out that it does not affect the error in any way, so I don’t show the logic) and standard object saving using:
```php
$cart = $this->documentManager->getRepository(Cart::class)->find('some_id');
$cart->setProducts([/* CartItem[] */]);
$this->documentManager->flush();
```

I also attach the config file (`config/packages/doctrine.yaml`):
```
doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
```

What could be the problem?
