### ISSUE TITLE
Inserting a document with existing Id doesn't throw an error

### ISSUE THREAD

**Issue by Valentinfe** [doctrine/mongodb-odm#2704]
|    Q        |   A
|------------ | -----
| Version     | 2.8.2

### Support Question

I'm actually trying to insert a document with an already existing Id in the collection and no error is thrown. In fact it replaces the previous document and merge the two documents EmbededMany. 

Here are some steps to reproduce this behavior:

1. A Dummy class to insert
```php
<?php

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

#[MongoDB\Document]
class Dummy
{
    #[MongoDB\Id(strategy: "UUID")]
    protected string $id;

    #[MongoDB\Field(type: "string")]
    protected string $text;

    /**
     * @param string $id
     */
    public function __construct(string $id, string $text)
    {
        $this->id   = $id;
        $this->text = $text;
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): Dummy
    {
        $this->id = $id;
        return $this;
    }

    public function getText(): string
    {
        return $this->text;
    }

    public function setText(string $text): Dummy
    {
        $this->text = $text;
        return $this;
    }
}
```

2. My controller that insert my dummy in mongo
```php
<?php

namespace App\Controller;

use App\Document\Dummy;
use Doctrine\ODM\MongoDB\DocumentManager;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use FOS\RestBundle\Controller\Annotations as Rest;
use OpenApi\Attributes as OA;


#[OA\Tag(name: 'dummy')]
#[Rest\Route('/api/dummy')]
class DummyController extends AbstractController
{
    public function __construct(
        private DocumentManager $dm,
    ){}

    #[Rest\Get('')]
    public function getVotes(Request $request): JsonResponse
    {
        $dummy = new Dummy("40a36a1f-b5aa-4fc9-ad7a-e0ac801d8976", "first test");
        $this->dm->persist($dummy);
        $this->dm->flush();

        return new JsonResponse();
    }
}
```

3. After the first call the dummy is properly created
![image](https://github.com/user-attachments/assets/32b2f8eb-9df6-4638-9203-7e6dcb0986cb)

4. I make a second call with the text value to "second test" and the first document is replaced by the new one without any error
![image](https://github.com/user-attachments/assets/b97708b4-ae2a-44c4-8da5-0b2ee9cd2675)

I don't know if it's actually a bug or if i'm missing something ?

FYI: If i try to insert a duplicate with mongosh, the unique index is properly working and throwing a duplicate key error.
![image](https://github.com/user-attachments/assets/700443ef-05fe-4c14-b998-8791f80016e6)

This my mongodb bundle configuration:
```yaml
doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(string:MONGODB_URL)%'
    default_database: '%env(string:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'

when@prod:
    doctrine_mongodb:
        auto_generate_proxy_classes: false
        auto_generate_hydrator_classes: false

```
