### ISSUE TITLE
Extra queries in logger

### ISSUE THREAD

**Issue by alexshelkov** [doctrine/mongodb-odm#471]
I have 2 entites:

```
Imr\Model\Order:
  collection: orders
  fields:
    id:
      id: true
  referenceOne:
    store:
      targetDocument: Imr\Model\Store
```

```
Imr\Model\Store:
  collection: stores
  repositoryClass: Imr\Model\Store\Repository
  fields:
    id:
      id: true
    token:
      type: string
```

When I try to exectue query:
```php
$orders = $m->getRepository('Imr\Model\Order')->findBy(array());

foreach ($orders as $o) {
    if ($o->getStore())
        var_dump($o->getStore()->getToken());
    }
}
```
Why logger logs 5 quersies instead of 2 (mongodb profiler shows only 2 queries)? Here queres which logged:
```
array (size=5)
  'find' => boolean true
  'query' => 
    array (size=0)
      empty
  'fields' => 
    array (size=0)
      empty
  'db' => string 'zf2_modules' (length=11)
  'collection' => string 'orders' (length=6)

array (size=5)
  'find' => boolean true
  'query' => 
    array (size=1)
      '_id' => 
        object(MongoId)[270]
          public '$id' => string '50e460037664bc2902000010' (length=24)
  'fields' => 
    array (size=0)
      empty
  'db' => string 'zf2_modules' (length=11)
  'collection' => string 'stores' (length=6)

array (size=4)
  'limit' => boolean true
  'limitNum' => int 1
  'query' => 
    array (size=1)
      '_id' => 
        object(MongoId)[270]
          public '$id' => string '50e460037664bc2902000010' (length=24)
  'fields' => 
    array (size=0)
      empty

array (size=4)
  'limit' => boolean true
  'limitNum' => int 1
  'query' => 
    array (size=1)
      '_id' => 
        object(MongoId)[270]
          public '$id' => string '50e460037664bc2902000010' (length=24)
  'fields' => 
    array (size=0)
      empty

array (size=4)
  'limit' => boolean true
  'limitNum' => int 1
  'query' => 
    array (size=1)
      '_id' => 
        object(MongoId)[270]
          public '$id' => string '50e460037664bc2902000010' (length=24)
  'fields' => 
    array (size=0)
      empty
```
What 3 extra queries mean?
