### ISSUE TITLE
Problem with idexes in YAML mapping

### ISSUE THREAD

**Issue by alexshelkov** [doctrine/mongodb-odm#510]
When I try to create indexes via YAML mapping I get an error:

``` yml
User:
  type: document
  collection: users
  fields:
    id:
      id: true
    email:
      type: string
      index: true
```

Argument 2 passed to Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo::addIndex() must be an array, boolean given, called in /Users/san/Sites/myprojects/ApptSimpleAuth/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php

AnnotationDriver works as expected.

Also maybe problem in docs, beacause this works as I expected:

```
    email:
      type: string
      index: []

```
