### ISSUE TITLE
Embedded documents not persisted without "type" option in yaml mapping

### ISSUE THREAD

**Issue by kaiwa** [doctrine/mongodb-odm#684]
Embedded documents are no more persisted (`isEmbeddedDocument` is `false`) without setting the `type` option to `embeddedDocument`:

```
    User:
      type: document
      embedOne:
        address:
          targetDocument: Address

    Address:
-----> type: embeddedDocument
```

AFAIK some time ago it was enough to specify the mapping on the parent class when using YAML; at least my app was working doing so and the <a href="http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/embedded-mapping.html">docs</a> show it that way too.

Was it an intentional change?
