### ISSUE TITLE
Undefined index: providers in UnitOfWork.php

### ISSUE THREAD

**Issue by aferrandini** [doctrine/mongodb-odm#721]
```
[Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined index: providers in ./vendor/doctrine/mongodb
  -odm/lib/Doctrine/ODM/MongoDB/UnitOfWork.php line 724
```

We're getting this error when using objects from unserialized from memcached.

In the example, the Competition contains an collection of CompetitionProviderIdentifiers which inherits ProviderIdentifier.

When we get the object from memcached, we add it to the UnitOfWork, so we can change it and make persist & flush for this object.
We get the Exception when we add any object to the UnitOfWork.

To solve the problem we've add this lines to the UnitOfWork class, but we're not sure if it's right:

``` php
// UnitOfWork.php
  721  if ($actualValue instanceof PersistentCollection) { 
  722      $owner = $actualValue->getOwner();
  723      if ($owner === null) { // cloned
+ 724          if (!isset ($class->fieldMappings[$propName])) {
+ 725              $class->fieldMappings[$propName] = array();
+ 726          }
  727          $actualValue->setOwner($document, $class->fieldMappings[$propName]);
  728      } elseif ($owner !== $document) { // no clone, we have to fix
  729          if ( ! $actualValue->isInitial
```

The Documents configuration:

``` yml
# Competition.mongodb.yml
SportBundle\Document\Competition:
    type: document
    collection: competitions
    repositoryClass: SportBundle\Document\CompetitionRepository
    fields:
        id:
            type: id
            id: true

        vocento_id:
            type: int

        name:
            type: string

        slug:
            type: string
            index: true
            length: 100
            gedmo:
                slug:
                    separator: -
                    fields:
                        - name
                    updatable: true
                    unique: true
    embedMany:
        providers:
            targetDocument: SportBundle\Document\CompetitionProviderIdentifier
```

``` yml
# CompetitionProviderIdentifier.mongodb.yml
SportBundle\Document\CompetitionProviderIdentifier:
    type: embeddedDocument
    inheritanceType: COLLECTION_PER_CLASS

    fields:
        season:
            type: string
            nullable: true

        active:
            type: boolean
            nullable: false
```

``` yml
# ProviderIndentifier.mongobd.yml
SportBundle\Document\ProviderIdentifier:
    type: embeddedDocument
    fields:
        id:
            type: id
            id: true
            strategy: NONE

        provider_id:
            type: int

    referenceOne:
        provider:
            targetDocument: ProviderBundle\Document\Provider
```

``` yml
# Provider.mongodb.yml
ProviderBundle\Document\Provider:
    type: document
    collection: providers
    repositoryClass: ProviderBundle\Document\ProviderRepository
    fields:
        id:
            type: id
            id: true

        name:
            type: string

        slug:
            index: true
            type: string
            length: 100
            gedmo:
                slug:
                    separator: -
                    fields:
                        - name
                    updatable: false
                    unique: true
```
