### ISSUE TITLE
AlsoLoad and NotSaved mappings for YAML

### ISSUE THREAD

**Issue by sbward** [doctrine/mongodb-odm#884]
The AlsoLoad and NotSaved features are not configurable through YAML. YamlDriver should be updated to support these migration features.

Here's an idea for how they can be supported:

``` yaml
My\Domain\Thing:
    type: document
    inheritanceType: SINGLE_COLLECTION
    fields:
        hash:
            id:  true
        customDescription:
            type: string
            name: custom_description
            alsoLoad: old_description
        notSavedField:
            name: not_saved_field
            notSaved: true
        createdDate:
            type: date
            name: created_date
        modifiedDate:
            type: date
            name: modified_date
    lifecycleCallbacks:
        prePersist: [ onPrePersist ]
        preUpdate: [ onPreUpdate ]
    alsoLoad:
        migrateSomeField: [ someField ]
```
